
CREATE TABLE urls (
	id INT NOT NULL AUTO_INCREMENT,
	url TEXT,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY (id)
);

ALTER TABLE urls AUTO_INCREMENT = 100;
